[package]
name = "gluon_language-server"
version = "0.5.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
description = "Language server providing completion for gluon"
license = "MIT"
repository = "https://github.com/gluon-lang/gluon_language-server"

[workspace]

[[bin]]
name = "gluon_debugger"
path = "src/debugger.rs"

[[bin]]
name = "gluon_language-server"
path = "src/main.rs"

[dependencies]
clap = "2.19.0"

log = "0.3.6"
env_logger = "0.3.3"

url = "1.2.0"
url_serde = "0.2.0"

jsonrpc-core = "7.0.0"
futures = "0.1.0"

serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"

languageserver-types = { git = "https://github.com/gluon-lang/languageserver-types", branch = "codify" }
debugserver-types = "0.3.0"

gluon = "0.5.0"

[dev-dependencies]
pretty_assertions = "0.2.0"
